apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-quarkus-app-24"
  annotations:
    argocd/app-name: my-quarkus-app-24-dev
    backstage.io/kubernetes-id: my-quarkus-app-24
    backstage.io/kubernetes-namespace: my-quarkus-app-24-dev
    github.com/project-slug: janus-demo-video/my-quarkus-app-24
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-h55hs.h55hs.sandbox385.opentlc.com/#https://github.com/janus-demo-video/my-quarkus-app-24?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-h55hs.h55hs.sandbox385.opentlc.com/#https://github.com/janus-demo-video/my-quarkus-app-24?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "m"
  providesApis:
    - "my-quarkus-app-24"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "my-quarkus-app-24"
spec:
  type: openapi
  lifecycle: production
  owner: "m"
  definition:
    $text: ./openapi.yaml